Repository BCSDLab/KOIN_ORDER_WEBVIEW, pull requests merged in 2025-05, with the labels that each got.

#6 [공통] 공통 컴포넌트 제작
  package.json
  pnpm-lock.yaml
  src/assets/Main/agriculture.svg
  src/assets/Main/arrow-back-icon.svg
  src/assets/Main/close-icon.svg
  src/assets/Main/home-icon.svg
  src/components/Layout/Header/index.tsx
  src/components/Portal/index.tsx
  src/components/UI/Badge/index.tsx
  src/components/UI/Button/index.tsx
  src/components/UI/Modal/BottomModal.tsx
  src/components/UI/Modal/index.tsx
  src/index.css
Labels: 🖊️ UI 개발

#12 [결제] 결제 메인 페이지
  src/App.tsx
  src/assets/Main/university-icon.svg
  src/assets/Payment/checkbox-icon.svg
  src/assets/Payment/input-delete-icon.svg
  src/components/Layout/Header/index.tsx
  src/components/Layout/PaymentLayout/index.tsx
  src/components/UI/Button/index.tsx
  src/components/UI/Modal/BottomModal.tsx
  src/index.css
  src/pages/Payment/components/ContactModal/ContactModal.tsx
  src/pages/Payment/components/StoreRequestModal/StoreRequestModal.tsx
  src/pages/Payment/index.tsx
Labels: ✨ Feature, 🖊️ UI 개발

#13 [결제] 결제 위젯 띄우기
  package.json
  pnpm-lock.yaml
  src/pages/Payment/components/Agreement/index.tsx
  src/pages/Payment/components/PaymentAmount/index.tsx
  src/pages/Payment/components/TossWidget/index.tsx
  src/pages/Payment/index.tsx
Labels: ✨ Feature, 🖊️ UI 개발

#23 [lint 설정] lint 룰 삭제, 스타일 파일 구분
  eslint.config.js
  src/index.css
  src/styles/base.css
  src/styles/component.css
  src/styles/font.css
  src/styles/theme.css
Labels: ⚙️ Setting
