Repository BCSDLab/KOIN_ORDER_WEBVIEW, pull requests merged in 2025-07, with the labels that each got.

#54 [결제] 교내/교외 배달 여부 API 연결 및 모달 추가
  src/api/shop/entity.ts
  src/api/shop/index.ts
  src/pages/Payment/components/AddressModal.tsx
  src/pages/Payment/components/DeliveryAddressSection.tsx
  src/pages/Payment/hooks/useDeliveryInfo.ts
  src/pages/Payment/index.tsx
  src/types/api/cart.ts
Labels: 📬 API, 🔨 Refactor

#51 [주문완료] 주문 취소 과정 페이지 추가
  src/App.tsx
  src/assets/OrderFinish/check-icon.svg
  src/components/Layout/Header/routeTitles.ts
  src/pages/OrderFinish/OrderCancel.tsx
  src/pages/OrderFinish/index.tsx
Labels: ✨ Feature, 🖊️ UI 개발

#60 [공통] 안드로이드 브릿지 구현 및 기존 브릿지 리팩토링
  src/App.tsx
  src/api/cart/index.ts
  src/components/Layout/Header/CartResetButton.tsx
  src/components/Layout/Header/index.tsx
  src/global.d.ts
  src/pages/OrderFinish/OrderCancel.tsx
  src/pages/Payment/hooks/useCart.ts
  src/stores/auth.ts
  src/styles/theme.css
  src/util/ts/bridge.ts
Labels: ✨ Feature, 🔨 Refactor

#75 [교내/교외 배달 주소] 주소 전역 상태 스토어 적용 및 리팩토링
  src/api/delivery/entity.ts
  src/api/delivery/index.ts
  src/pages/Delivery/Campus/AddressTypeDropdown.tsx
  src/pages/Delivery/Campus/index.tsx
  src/pages/Delivery/Outside/DetailAddress.tsx
  src/pages/Delivery/Outside/index.tsx
  src/pages/Delivery/components/RiderRequestModal.tsx
  src/pages/Delivery/hooks/useGetRiderRequest.ts
  src/pages/Delivery/hooks/useUserDeliveryAddress.ts
  src/pages/Payment/components/ContactModal.tsx
  src/pages/Payment/components/DeliveryAddressSection.tsx
  src/pages/Payment/index.tsx
  src/stores/useOrderStore.ts
  src/types/api/deliveryCampus.ts
Labels: 🔨 Refactor

#77 [교내 배달] 배달 받는 장소와 네이버 지도 연동
  src/pages/Delivery/Campus/AddressTypeDropdown.tsx
  src/pages/Delivery/Campus/index.tsx
  src/pages/Delivery/hooks/useNaverMap.ts
  src/stores/useOrderStore.ts
Labels: ✨ Feature

#83 [장바구니&메뉴담기] 장바구니 페이지 내에서 옵션 변경 기능 연결
  src/api/cart/entity.ts
  src/api/cart/index.ts
  src/api/shop/entity.ts
  src/pages/Cart/components/CartItem.tsx
  src/pages/Cart/hooks/useGetCartItemOptions.ts
  src/pages/Cart/hooks/useUpdateCartItemOptions.ts
  src/pages/Cart/index.tsx
  src/pages/Shop/MenuDetail/index.tsx
  src/pages/Shop/components/AddToCartBottomModal.tsx
  src/pages/Shop/hooks/useMenuSelection.ts
Labels: ✨ Feature

#85 [공통] 브릿지 연결
  src/api/cart/index.ts
  src/api/delivery/index.ts
  src/api/payments/index.ts
  src/pages/Cart/index.tsx
  src/pages/OrderFinish/hooks/useCancelPayment.ts
  src/pages/Payment/components/ShopLocationMap.tsx
  src/pages/Shop/components/Header.tsx
Labels: ✨ Feature, 🔨 Refactor

#87 [장바구니] 비회원 장바구니 관련 모달 추가
  src/pages/Shop/MenuDetail/index.tsx
  src/pages/Shop/components/LoginRequiredModal.tsx
Labels: ✨ Feature, 🖊️ UI 개발

#93 [주문] 연락처 초기화 오류
  src/pages/Payment/index.tsx
  src/stores/useOrderStore.ts
Labels: 🐞 BugFix

#97 [메뉴담기&장바구니] 비로그인 상태에서 메뉴 담기 시 정보 저장 및 로그인 후 장바구니에 유지
  src/pages/Cart/index.tsx
  src/pages/Shop/MenuDetail/index.tsx
  src/pages/Shop/components/LoginRequiredModal.tsx
  src/pages/Shop/hooks/useAddCart.ts
Labels: ✨ Feature

#99 [결제] 로띠 추가
  package.json
  pnpm-lock.yaml
  src/assets/Payment/paying.json
  src/pages/OrderFinish/index.tsx
Labels: 🖊️ UI 개발

#103 [장바구니&결제] QA 이슈 수정
  src/pages/Delivery/Campus/index.tsx
  src/pages/Delivery/Outside/DetailAddress.tsx
  src/pages/Delivery/components/RiderRequestModal.tsx
  src/pages/OrderFinish/OrderCancel.tsx
  src/pages/Payment/components/ContactModal.tsx
  src/pages/Payment/components/StoreRequestModal.tsx
  src/pages/Payment/index.tsx
  src/pages/Shop/MenuDetail/index.tsx
  src/pages/Shop/index.tsx
Labels: ❗QA issue
