Repository BCSDLab/KOIN_ORDER_WEBVIEW, pull requests merged in 2025-08, with the labels that each got.

#119 [주문,주변상점] api 연결 리뷰 수정
  src/App.tsx
  src/api/shop/entity.ts
  src/api/shop/index.ts
  src/assets/Shop/empty_thumbnail.svg
  src/components/Layout/Header/routeTitles.ts
  src/pages/Cart/components/CartItem.tsx
  src/pages/Cart/index.tsx
  src/pages/Delivery/Outside/DetailAddress.tsx
  src/pages/Shop/OrderableShopView.tsx
  src/pages/Shop/ShopDetail/components/OrderableShopDetail.tsx
  src/pages/Shop/ShopDetail/components/UnOrderableShopDetail.tsx
  src/pages/Shop/ShopDetail/index.tsx
  src/pages/Shop/UnOrderableShopView.tsx
  src/pages/Shop/components/ImageCarousel.tsx
  src/pages/Shop/components/ImageViewer.tsx
  src/pages/Shop/components/LoginRequiredModal.tsx
  src/pages/Shop/components/MenuOptions.tsx
  src/pages/Shop/components/MenuPriceSelects.tsx
  src/pages/Shop/components/ShopMenuGroups.tsx
  src/pages/Shop/components/ShopMenus.tsx
  src/pages/Shop/components/ShopSummary.tsx
  src/pages/Shop/components/TypeIcon.tsx
  src/pages/Shop/hooks/useGetShopDetail.ts
  src/pages/Shop/hooks/useGetShopInfo.ts
  src/pages/Shop/hooks/useMenuGroupScroll.ts
  src/pages/Shop/hooks/useMenuSelection.ts
Labels: 📬 API, ✨ Feature

#127 [결제] 연락처 모달 디자인 및 기능정의서 변경 사항 적용
  src/components/UI/BottomModal/BottomModal.tsx
  src/pages/Payment/components/ContactModal.tsx
  src/pages/Shop/components/ImageViewer.tsx
  src/styles/theme.css
  src/util/hooks/useHandleOutside.ts
Labels: 🔨 Refactor

#129 [결제] 3차 QA 이슈 수정
  src/components/Layout/Header/index.tsx
  src/pages/Payment/components/ContactModal.tsx
  src/pages/Payment/index.tsx
  src/util/ts/bridge.ts
Labels: ❗QA issue
